# 1. Create a 3x3x3 array with random values 

In [51]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,5,2],[4,6,8],[1,5,8]],[[2,2,7],[2,3,5],[3,6,8]]])
print(a)
print(type(a))
print(a.shape)
a

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 5 2]
  [4 6 8]
  [1 5 8]]

 [[2 2 7]
  [2 3 5]
  [3 6 8]]]
<class 'numpy.ndarray'>
(3, 3, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 5, 2],
        [4, 6, 8],
        [1, 5, 8]],

       [[2, 2, 7],
        [2, 3, 5],
        [3, 6, 8]]])

In [52]:
# Method 2 
np.random.random((3,3,3))

array([[[0.37722327, 0.09952286, 0.55273388],
        [0.70680088, 0.64205522, 0.99491466],
        [0.81574095, 0.27141234, 0.50231849]],

       [[0.93876328, 0.19089082, 0.2231069 ],
        [0.19013512, 0.48803676, 0.21131498],
        [0.83560134, 0.4670088 , 0.85984063]],

       [[0.04790248, 0.45958393, 0.29404926],
        [0.80639372, 0.83731701, 0.34581801],
        [0.27021245, 0.62985336, 0.16369518]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [53]:
b = np.zeros((5,5))
b[1][0] += 1
b[2][1] += 2
b[3][2] += 3
b[4][3] += 4
print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [54]:
c = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2 == 0 :
            c[i][j] = 1
print(c)
        

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# 4. Normalize a 5x5 random matrix

In [55]:
d= np.random.random((3,3))

print(d)
dmax = d.max()
dmin = d.min()
d = (d - dmin)/(dmax - dmin)

print("\n\n",d)

[[0.46239254 0.64827767 0.52049601]
 [0.08805238 0.00719702 0.88735964]
 [0.14511307 0.65865492 0.41857261]]


 [[0.51717206 0.72836613 0.58318653]
 [0.09186411 0.         1.        ]
 [0.15669383 0.74015629 0.46738589]]


# 5.  How to find common values between two arrays?

In [56]:
# Method 1

e = np.array([9,10,11])
count = 0
for i in range(a.shape[0]): 
    for j in range(a.shape[1]): 
        for k in range(a.shape[2]): 
            if a[i][j][k] in e.flatten():
                count = count+1 
                print(a[i][j][k])
    
    
        
print("The total number of common values between the 2 arrays is: ", count)

9
The total number of common values between the 2 arrays is:  1


In [57]:
# Method 2

f = np.array([7,8,9])
for i in e.flatten():
    if i in f.flatten():
        print(i)


9


In [66]:
# Method 3

print(np.intersect1d(e,f))
print(np.intersect1d(a,b))

[9]
[1. 2. 3. 4.]


# 6.How to get the dates of yesterday, today and tomorrow?

In [70]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yestraday's Date: ",yesterday)
today     = np.datetime64('today')
print("Today's Date: ",today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow's Date: ",tomorrow)

Yestraday's Date:  2020-07-23
Today's Date:  2020-07-24
Tomorrow's Date:  2020-07-25


# 7. Consider two random array A and B, check if they are equal

In [72]:
A = np.random.random((2,2))
B = np.random.random((2,2))
print((A==B).all()) # The whole array or matrix comparison
print(A==B) # Element-wise comparison

False
[[False False]
 [False False]]


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [83]:
# Method 1 

v = np.random.random(10)
print(v)
print(v.max())
for i in range(len(v)):
    if v[i] == v.max():
        v[i] = 0
        break
print(v)

[0.66125321 0.52640083 0.58646049 0.0368903  0.46683739 0.17692483
 0.60441036 0.08101305 0.468353   0.06030743]
0.6612532100310463
[0.         0.52640083 0.58646049 0.0368903  0.46683739 0.17692483
 0.60441036 0.08101305 0.468353   0.06030743]


In [84]:
v1 = np.random.random(10)
v1[v1.argmax()] = 0
print(v1)

[0.9103011  0.1312613  0.62452938 0.55924173 0.4886147  0.83115886
 0.81949886 0.         0.68593979 0.19338092]


# 9. How to print all the values of an array?

In [85]:
l = np.random.random((5,5,5))
for i in range(l.shape[0]):
    for j in range(l.shape[1]):
        for k in range(l.shape[2]):
            print(l[i][j][k])

0.08741913890381126
0.36747444400393847
0.5620573010525024
0.26655239874775594
0.999427760478386
0.3910124770935429
0.8434939314419366
0.36437014993693306
0.7583813495567397
0.12368805492737123
0.33330625578011697
0.3895454623403396
0.2447984028786735
0.4985200400804851
0.5602215796002077
0.050496553267409094
0.6176862255735918
0.13630016718651006
0.23822331319809809
0.5021895993240405
0.6233282373654452
0.5473074559337285
0.6308002043965242
0.5308351384800438
0.3826492686253824
0.6835606513628057
0.3246525370920228
0.6244971518868027
0.36079407452853207
0.2446954487712537
0.656513000518949
0.28469081370986304
0.8839358560520747
0.6315083937436318
0.7739133948980175
0.40781013699191404
0.5048899638526732
0.8361362679964717
0.4258142420753148
0.6613206985766186
0.26851068127376154
0.3121135989262558
0.12906339391417954
0.2547128554411143
0.8328659660232557
0.02443668809231836
0.6282808631812611
0.4200667869189618
0.9111589511054357
0.6961246447999904
0.2879568091750875
0.176104504642665

# 10.Subtract the mean of each row of a matrix

In [122]:
import scipy
from scipy import stats
a = np.random.random((np.random.randint(3,5),np.random.randint(3,5)))
m = []

print("\n\n\n",a)

for i in range(a.shape[0]):
    b = np.array(a[i])
    m.append(np.mean(a[i]))
o = np.ones_like(a)
for i in range(o.shape[0]):
    o[i] = o[i]*m[i]
print("\n\n\nThe list of means of each row: \n",m)
print("\n\n\nOnes like a multiplied by the mean of the row: \n", o)
print("\n\n\n The resulting matrix is: \n",a-o)




 [[0.26807427 0.9077762  0.28713489 0.78202798]
 [0.77569845 0.10357218 0.48999977 0.02325329]
 [0.39031407 0.4876314  0.17230524 0.3690699 ]
 [0.74558093 0.96292812 0.46270125 0.92102869]]



The list of means of each row: 
 [0.5612533375676168, 0.3481309214793491, 0.35483015294496023, 0.7730597459630333]



Ones like a multiplied by the mean of the row: 
 [[0.56125334 0.56125334 0.56125334 0.56125334]
 [0.34813092 0.34813092 0.34813092 0.34813092]
 [0.35483015 0.35483015 0.35483015 0.35483015]
 [0.77305975 0.77305975 0.77305975 0.77305975]]



 The resulting matrix is: 
 [[-0.29317906  0.34652287 -0.27411844  0.22077464]
 [ 0.42756753 -0.24455874  0.14186885 -0.32487763]
 [ 0.03548392  0.13280125 -0.18252491  0.01423974]
 [-0.02747882  0.18986837 -0.3103585   0.14796894]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [131]:
v = [2,4,6,8,10]

In [133]:
V = np.random.randint(1,100,20)
print(V)
for i in v:
    V[i] = V[i]+1
print(V)

[ 6 23 34 98 26 84 31 49 10 83 65 30 31 89 32 46 88  6 94 25]
[ 6 23 35 98 27 84 32 49 11 83 66 30 31 89 32 46 88  6 94 25]


# 12.How to get the diagonal of a dot product?

In [89]:
q = np.random.random((2,2))
r = np.random.random((2,2))
s = q.dot(r)
l=[]
for i in range(s.shape[0]):
    for j in range(s.shape[1]):
        if i ==j:
            l.append(s[i][j])
print("The diagonal elements of the dot product are: ",l)

The diagonal elements of the dot product are:  [0.20549578320446088, 0.14033628423169273]


# 13.How to find the most frequent value in an array?

In [130]:

from scipy import stats
a = np.random.randint(1,20,25)
print(a)
m = stats.mode(a)
print(m)

[ 2  9 14  8  6  9 14  5  3 17 17  9 12 14 16 12 14  6 18 13  2  7 13  1
  4]
ModeResult(mode=array([14]), count=array([4]))


# 14.How to get the n largest values of an array

In [141]:
t = np.random.randint(1,10000,1000)
n = int(input("Please enter the number of largest value's you want to see?"))
print ((t[np.argsort(t)[-n:]])[::-1])

Please enter the number of largest value's you want to see?30
[9957 9945 9930 9921 9915 9915 9910 9908 9900 9896 9892 9875 9875 9843
 9837 9832 9831 9773 9759 9737 9722 9718 9717 9716 9707 9694 9694 9672
 9666 9664]


# 15.How to create a record array from a regular array?

In [146]:
a1=np.array([10,20,30,40])
a2=np.array(['Orange','Grape','Banana','Apple'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3])
print(result)


[(10, 'Orange', 12.2) (20, 'Grape', 15. ) (30, 'Banana', 20. )
 (40, 'Apple', 40. )]
